/**
 * Phase 3.3 — prefill from analyzed reel.
 *
 * Covers:
 *   - "분석 결과 가져오기" button visible in editor top bar
 *   - Ctrl+I opens PrefillDialog
 *   - Empty state when listMyReels returns 0
 *   - Loaded state — grid renders + metadata enriches
 *   - Search filter works
 *   - 401 on listMyReels triggers token refresh
 *   - End-to-end pick → metadata + analysis + download (mocked) → media added,
 *     video clip created, captions populated, beats applied
 *   - addCaptions bulk store action behaves
 */
import { expect, test } from '@playwright/test'
import { launchElectron, type LaunchedApp } from '../helpers/launch'
import { openAiMenu } from '../helpers/topbar'

// Pull the fixture mp4 path generated by globalSetup. We point the mocked
// download IPC at this file so the rest of the flow (probe, thumbnail) sees a
// real on-disk video.
function getFixturePath(): string {
  const p = process.env.E2E_FIXTURE_MP4
  if (!p) throw new Error('E2E_FIXTURE_MP4 not set — globalSetup failed')
  return p
}

test.describe('@phase-3-prefill editor top bar entry point', () => {
  let launched: LaunchedApp | null = null

  test.beforeEach(async () => {
    launched = await launchElectron()
  })

  test.afterEach(async () => {
    if (launched) {
      try {
        await launched.app.close()
      } catch {
        /* ignore */
      }
      launched = null
    }
  })

  test('button renders in editor top bar', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched
    await page.locator('[data-testid="open-editor-button"]').click()
    await expect(page.locator('[data-testid="editor-page"]')).toBeVisible()
    await openAiMenu(page)
    await expect(
      page.locator('[data-testid="open-prefill-dialog"]')
    ).toBeVisible()
    await expect(
      page.locator('[data-testid="open-prefill-dialog"]')
    ).toContainText('분석 결과 가져오기')
  })

  test('Ctrl+I opens prefill dialog', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched

    // Stub listMyReels — return empty so we don't hit network and we land in
    // the empty state immediately.
    await page.evaluate(() => {
      window.fetch = ((input: RequestInfo | URL) => {
        const url = typeof input === 'string' ? input : (input as Request).url || String(input)
        if (url.includes('/api/reels')) {
          return Promise.resolve(
            new Response('[]', {
              status: 200,
              headers: { 'Content-Type': 'application/json' }
            })
          )
        }
        return Promise.resolve(new Response('{}', { status: 200 }))
      }) as typeof fetch
    })

    await page.locator('[data-testid="open-editor-button"]').click()
    await expect(page.locator('[data-testid="editor-page"]')).toBeVisible()

    // Trigger Ctrl+I — must be on the body / not in an input.
    await page.locator('body').click({ position: { x: 10, y: 10 } })
    await page.keyboard.press('Control+i')
    await expect(page.locator('[data-testid="prefill-dialog"]')).toBeVisible()
  })

  test('button click opens dialog with loading state', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched

    // Stub fetch with a slow response so we can observe the loading state.
    await page.evaluate(() => {
      window.fetch = ((input: RequestInfo | URL) => {
        const url = typeof input === 'string' ? input : (input as Request).url || String(input)
        if (url.includes('/api/reels')) {
          return new Promise((resolve) => {
            setTimeout(() => {
              resolve(
                new Response('[]', {
                  status: 200,
                  headers: { 'Content-Type': 'application/json' }
                })
              )
            }, 800)
          })
        }
        return Promise.resolve(new Response('{}', { status: 200 }))
      }) as typeof fetch
    })

    await page.locator('[data-testid="open-editor-button"]').click()
    await openAiMenu(page)
    await page.locator('[data-testid="open-prefill-dialog"]').click()
    await expect(page.locator('[data-testid="prefill-loading"]')).toBeVisible()
  })
})

test.describe('@phase-3-prefill list + filter + pagination', () => {
  let launched: LaunchedApp | null = null

  test.beforeEach(async () => {
    launched = await launchElectron()
  })

  test.afterEach(async () => {
    if (launched) {
      try {
        await launched.app.close()
      } catch {
        /* ignore */
      }
      launched = null
    }
  })

  test('shows empty state when listMyReels returns 0', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched

    await page.evaluate(() => {
      window.fetch = ((input: RequestInfo | URL) => {
        const url = typeof input === 'string' ? input : (input as Request).url || String(input)
        if (url.includes('/api/reels')) {
          return Promise.resolve(new Response('[]', { status: 200 }))
        }
        return Promise.resolve(new Response('{}', { status: 200 }))
      }) as typeof fetch
    })

    await page.locator('[data-testid="open-editor-button"]').click()
    await openAiMenu(page)
    await page.locator('[data-testid="open-prefill-dialog"]').click()
    await expect(page.locator('[data-testid="prefill-empty"]')).toBeVisible()
    await expect(page.locator('[data-testid="prefill-empty"]')).toContainText(
      '분석된 릴스가 없습니다'
    )
  })

  test('renders reel grid + enriches with metadata', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched

    await page.evaluate(() => {
      const reels = [
        { shortcode: 'ABC123', url: 'u1', collected_at: '2026-05-01' },
        { shortcode: 'DEF456', url: 'u2', collected_at: '2026-05-02' }
      ]
      const metadataByCode: Record<string, unknown> = {
        ABC123: {
          shortcode: 'ABC123',
          author_username: 'alice',
          caption_text: 'Cool reel about food',
          video_duration: 12.5,
          thumbnail_url: 'https://example.com/abc.jpg',
          video_url: 'https://example.com/abc.mp4'
        },
        DEF456: {
          shortcode: 'DEF456',
          author_username: 'bob',
          caption_text: 'Travel vlog',
          video_duration: 24.0,
          thumbnail_url: 'https://example.com/def.jpg',
          video_url: 'https://example.com/def.mp4'
        }
      }
      window.fetch = ((input: RequestInfo | URL) => {
        const url = typeof input === 'string' ? input : (input as Request).url || String(input)
        if (url.includes('/api/reels')) {
          return Promise.resolve(
            new Response(JSON.stringify(reels), {
              status: 200,
              headers: { 'Content-Type': 'application/json' }
            })
          )
        }
        const m = url.match(/\/api\/metadata\/([A-Za-z0-9_]+)/)
        if (m) {
          const sc = m[1]
          const md = metadataByCode[sc]
          if (md) {
            return Promise.resolve(
              new Response(JSON.stringify(md), {
                status: 200,
                headers: { 'Content-Type': 'application/json' }
              })
            )
          }
          return Promise.resolve(new Response('{}', { status: 404 }))
        }
        return Promise.resolve(new Response('{}', { status: 200 }))
      }) as typeof fetch
    })

    await page.locator('[data-testid="open-editor-button"]').click()
    await openAiMenu(page)
    await page.locator('[data-testid="open-prefill-dialog"]').click()
    await expect(page.locator('[data-testid="prefill-grid"]')).toBeVisible()
    await expect(
      page.locator('[data-testid="prefill-card-ABC123"]')
    ).toBeVisible()
    await expect(
      page.locator('[data-testid="prefill-card-DEF456"]')
    ).toBeVisible()
    // Metadata enrichment populates author + caption + duration eventually.
    await expect(
      page.locator('[data-testid="prefill-card-ABC123"]')
    ).toContainText('alice')
    await expect(
      page.locator('[data-testid="prefill-card-ABC123"]')
    ).toContainText('Cool reel')
  })

  test('search filter narrows visible cards by author/caption/shortcode', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched

    await page.evaluate(() => {
      const reels = [
        { shortcode: 'ABC123', url: 'u1', collected_at: '2026-05-01' },
        { shortcode: 'DEF456', url: 'u2', collected_at: '2026-05-02' },
        { shortcode: 'GHI789', url: 'u3', collected_at: '2026-05-03' }
      ]
      const metadataByCode: Record<string, unknown> = {
        ABC123: { shortcode: 'ABC123', author_username: 'alice', caption_text: 'food' },
        DEF456: { shortcode: 'DEF456', author_username: 'bob', caption_text: 'travel' },
        GHI789: { shortcode: 'GHI789', author_username: 'carol', caption_text: 'music' }
      }
      window.fetch = ((input: RequestInfo | URL) => {
        const url = typeof input === 'string' ? input : (input as Request).url || String(input)
        if (url.includes('/api/reels')) {
          return Promise.resolve(new Response(JSON.stringify(reels), { status: 200 }))
        }
        const m = url.match(/\/api\/metadata\/([A-Za-z0-9_]+)/)
        if (m) {
          const md = metadataByCode[m[1]]
          if (md) return Promise.resolve(new Response(JSON.stringify(md), { status: 200 }))
        }
        return Promise.resolve(new Response('{}', { status: 200 }))
      }) as typeof fetch
    })

    await page.locator('[data-testid="open-editor-button"]').click()
    await openAiMenu(page)
    await page.locator('[data-testid="open-prefill-dialog"]').click()
    // Wait for metadata to populate so the search filter has something to match.
    await expect(
      page.locator('[data-testid="prefill-card-ABC123"]')
    ).toContainText('alice')
    await expect(
      page.locator('[data-testid="prefill-card-DEF456"]')
    ).toContainText('bob')

    await page.locator('[data-testid="prefill-search"]').fill('travel')
    await expect(
      page.locator('[data-testid="prefill-card-DEF456"]')
    ).toBeVisible()
    await expect(
      page.locator('[data-testid="prefill-card-ABC123"]')
    ).toHaveCount(0)
    await expect(
      page.locator('[data-testid="prefill-card-GHI789"]')
    ).toHaveCount(0)

    // Clear filter — all three back.
    await page.locator('[data-testid="prefill-search"]').fill('')
    await expect(
      page.locator('[data-testid="prefill-card-ABC123"]')
    ).toBeVisible()
    await expect(
      page.locator('[data-testid="prefill-card-GHI789"]')
    ).toBeVisible()
  })
})

test.describe('@phase-3-prefill orchestration end-to-end', () => {
  let launched: LaunchedApp | null = null

  test.beforeEach(async () => {
    launched = await launchElectron()
  })

  test.afterEach(async () => {
    if (launched) {
      try {
        await launched.app.close()
      } catch {
        /* ignore */
      }
      launched = null
    }
  })

  test('prefillFromReel populates media + clip + captions + beats', async () => {
    if (!launched) throw new Error('launch failed')
    const { app, page } = launched

    // Mock download IPC in main process — return the test fixture as the
    // "downloaded" file. We REPLACE the registered handler so the renderer
    // can call window.electron.download.downloadVideoToTemp normally.
    const fixturePath = getFixturePath()
    await app.evaluate(async ({ ipcMain }, fixture) => {
      ipcMain.removeHandler('download:downloadVideoToTemp')
      ipcMain.handle('download:downloadVideoToTemp', async () => ({
        ok: true,
        localPath: fixture,
        sizeBytes: 1024 * 100
      }))
    }, fixturePath)

    // Mock the renderer-side fetch for metadata + analysis.
    await page.evaluate(() => {
      const sentences = [
        { start: 0.0, end: 1.5, text: 'hello world' },
        { start: 1.5, end: 3.0, text: 'this is a test' },
        { start: 3.0, end: 4.5, text: 'caption three' }
      ]
      const proAudio = {
        duration_sec: 5,
        bpm: 128,
        beat_timeline: [0.0, 0.47, 0.94, 1.41, 1.88, 2.35, 2.82, 3.29, 3.76, 4.23],
        bgm_segments: [{ start: '0', end: '5', state: 'playing', mood: 'upbeat' }],
        emotion_timeline: [{ start: '0', end: '5', emotion: 'happy', intensity: 0.8, source: 'music' }]
      }
      const metadata = {
        shortcode: 'TEST01',
        author_username: 'tester',
        caption_text: 'integration test reel',
        video_duration: 5,
        video_url: 'https://example.com/test01.mp4',
        thumbnail_url: 'https://example.com/test01.jpg'
      }
      window.fetch = ((input: RequestInfo | URL) => {
        const url = typeof input === 'string' ? input : (input as Request).url || String(input)
        if (url.includes('/api/metadata/TEST01')) {
          return Promise.resolve(
            new Response(JSON.stringify(metadata), {
              status: 200,
              headers: { 'Content-Type': 'application/json' }
            })
          )
        }
        if (url.includes('/api/extra/TEST01')) {
          return Promise.resolve(
            new Response(
              JSON.stringify({ sentences, pro_audio: proAudio }),
              { status: 200, headers: { 'Content-Type': 'application/json' } }
            )
          )
        }
        return Promise.resolve(new Response('{}', { status: 200 }))
      }) as typeof fetch
    })

    // Make sure the editor mounts (so testBridge is installed).
    await page.locator('[data-testid="open-editor-button"]').click()
    await expect(page.locator('[data-testid="editor-page"]')).toBeVisible()

    // Reset to a pristine project — userData/project.json persists between
    // test runs so previous media would otherwise bleed into mediaCount.
    await page.evaluate(() => {
      const w = window as unknown as { __reelsStore: { createNew: () => void } }
      w.__reelsStore.createNew()
    })

    // Drive prefillFromReel via the test bridge.
    const result = await page.evaluate(async () => {
      const w = window as unknown as {
        __reelsApi: {
          prefillFromReel: (
            sc: string
          ) => Promise<{
            ok: boolean
            captionsAdded?: number
            beatsAdded?: number
            durationMs?: number
            bgmSegmentsDetected?: number
            error?: string
          }>
        }
      }
      return w.__reelsApi.prefillFromReel('TEST01')
    })

    expect(result.ok).toBe(true)
    expect(result.captionsAdded).toBe(3)
    // prefillFromReel reports how many beats IT loaded; Editor's bpm effect
    // may later regenerate from BPM+duration. We assert the prefill-side count.
    expect(result.beatsAdded).toBe(10)
    expect(result.bgmSegmentsDetected).toBe(1)
    expect(result.durationMs).toBeGreaterThanOrEqual(4500)

    // Verify store state — media + clip + caption clips.
    const storeState = await page.evaluate(() => {
      const w = window as unknown as {
        __reelsStore: { state: () => unknown }
        __reelsTimelineUi: { getState: () => unknown }
      }
      const s = w.__reelsStore.state() as {
        project: {
          tracks: { kind: string; clips: { kind: string }[] }[]
          media: Record<string, unknown>
        }
      }
      const ui = w.__reelsTimelineUi.getState() as {
        beats: number[]
        bpm: number
        beatSnapEnabled: boolean
      }
      const mediaCount = Object.keys(s.project.media).length
      const videoTrack = s.project.tracks.find((t) => t.kind === 'video')
      const captionTrack = s.project.tracks.find((t) => t.kind === 'caption')
      return {
        mediaCount,
        videoClipCount: videoTrack ? videoTrack.clips.length : 0,
        captionClipCount: captionTrack ? captionTrack.clips.length : 0,
        beats: ui.beats.length,
        bpm: ui.bpm,
        beatSnap: ui.beatSnapEnabled
      }
    })
    expect(storeState.mediaCount).toBe(1)
    expect(storeState.videoClipCount).toBe(1)
    expect(storeState.captionClipCount).toBe(3)
    // The Editor's BPM-effect re-derives beats at period=60000/128≈468.75ms
    // for a 5s clip, yielding ~11 beats. We assert "at least 10" so the
    // assertion is robust regardless of which side wins the last write.
    expect(storeState.beats).toBeGreaterThanOrEqual(10)
    expect(storeState.bpm).toBe(128)
    expect(storeState.beatSnap).toBe(true)
  })

  test('prefillFromReel surfaces error when download fails', async () => {
    if (!launched) throw new Error('launch failed')
    const { app, page } = launched

    await app.evaluate(async ({ ipcMain }) => {
      ipcMain.removeHandler('download:downloadVideoToTemp')
      ipcMain.handle('download:downloadVideoToTemp', async () => ({
        ok: false,
        error: 'simulated_failure'
      }))
    })

    await page.evaluate(() => {
      window.fetch = ((input: RequestInfo | URL) => {
        const url = typeof input === 'string' ? input : (input as Request).url || String(input)
        if (url.includes('/api/metadata/FAIL01')) {
          return Promise.resolve(
            new Response(
              JSON.stringify({
                shortcode: 'FAIL01',
                video_url: 'https://example.com/fail.mp4'
              }),
              { status: 200 }
            )
          )
        }
        if (url.includes('/api/extra/FAIL01')) {
          return Promise.resolve(
            new Response(JSON.stringify({ sentences: [], pro_audio: null }), {
              status: 200
            })
          )
        }
        return Promise.resolve(new Response('{}', { status: 200 }))
      }) as typeof fetch
    })

    await page.locator('[data-testid="open-editor-button"]').click()
    await expect(page.locator('[data-testid="editor-page"]')).toBeVisible()

    const result = await page.evaluate(async () => {
      const w = window as unknown as {
        __reelsApi: {
          prefillFromReel: (
            sc: string
          ) => Promise<{ ok: boolean; error?: string; step?: string }>
        }
      }
      return w.__reelsApi.prefillFromReel('FAIL01')
    })
    expect(result.ok).toBe(false)
    expect(result.step).toBe('download')
    expect(result.error || '').toContain('simulated_failure')
  })
})

test.describe('@phase-3-prefill bulk store action', () => {
  let launched: LaunchedApp | null = null

  test.beforeEach(async () => {
    launched = await launchElectron()
  })

  test.afterEach(async () => {
    if (launched) {
      try {
        await launched.app.close()
      } catch {
        /* ignore */
      }
      launched = null
    }
  })

  test('addCaptions appends in a single store update', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched
    // Editor needs to mount so the test bridge is wired.
    await page.locator('[data-testid="open-editor-button"]').click()
    await expect(page.locator('[data-testid="editor-page"]')).toBeVisible()
    // Reset project so prior-test captions don't leak in.
    await page.evaluate(() => {
      const w = window as unknown as { __reelsStore: { createNew: () => void } }
      w.__reelsStore.createNew()
    })

    const result = await page.evaluate(() => {
      const w = window as unknown as {
        __reelsStore: {
          state: () => {
            project: { tracks: { kind: string; id: string; clips: unknown[] }[] }
            getCaptionTrackId: () => string | null
          }
          addCaptions: (caps: unknown[]) => void
          newId: () => string
        }
      }
      const store = w.__reelsStore
      const trackId = store.state().getCaptionTrackId()
      if (!trackId) throw new Error('no caption track')
      const caps = []
      for (let i = 0; i < 50; i++) {
        caps.push({
          id: store.newId(),
          kind: 'caption',
          trackId,
          startMs: i * 500,
          endMs: i * 500 + 400,
          spans: [{ text: `cap ${i}` }],
          style: {
            preset: 'bottom-center',
            fontSize: 48,
            align: 'center',
            yPosition: 0.85,
            background: 'none'
          }
        })
      }
      store.addCaptions(caps)
      const captionTrack = store.state().project.tracks.find((t) => t.kind === 'caption')
      return captionTrack?.clips.length || 0
    })
    expect(result).toBe(50)
  })

  test('addCaptions filters non-caption clips defensively', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched
    await page.locator('[data-testid="open-editor-button"]').click()
    await expect(page.locator('[data-testid="editor-page"]')).toBeVisible()

    const result = await page.evaluate(() => {
      const w = window as unknown as {
        __reelsStore: {
          state: () => {
            project: { tracks: { kind: string; id: string; clips: unknown[] }[] }
            getCaptionTrackId: () => string | null
          }
          addCaptions: (caps: unknown[]) => void
          newId: () => string
        }
      }
      const store = w.__reelsStore
      const trackId = store.state().getCaptionTrackId()
      const before =
        store.state().project.tracks.find((t) => t.kind === 'caption')?.clips
          .length || 0
      store.addCaptions([
        // valid caption
        {
          id: store.newId(),
          kind: 'caption',
          trackId,
          startMs: 0,
          endMs: 500,
          spans: [{ text: 'good' }],
          style: {
            preset: 'bottom-center',
            fontSize: 48,
            align: 'center',
            yPosition: 0.85,
            background: 'none'
          }
        },
        // non-caption — should be filtered
        { id: 'fake', kind: 'media', startMs: 0, endMs: 100 },
        null
      ])
      const after =
        store.state().project.tracks.find((t) => t.kind === 'caption')?.clips
          .length || 0
      return { before, after }
    })
    expect(result.after - result.before).toBe(1)
  })
})

test.describe('@phase-3-prefill auth refresh', () => {
  let launched: LaunchedApp | null = null

  test.beforeEach(async () => {
    launched = await launchElectron()
  })

  test.afterEach(async () => {
    if (launched) {
      try {
        await launched.app.close()
      } catch {
        /* ignore */
      }
      launched = null
    }
  })

  test('401 on listMyReels triggers token refresh + retry', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched

    await page.evaluate(() => {
      const w = window as unknown as { __apiHits: number }
      w.__apiHits = 0
      const header = btoa(JSON.stringify({ alg: 'HS256', typ: 'JWT' }))
      const payload = btoa(
        JSON.stringify({
          sub: '00000000-0000-0000-0000-000000000001',
          email: 'e2e@reels-bench.local',
          exp: Math.floor(Date.now() / 1000) + 24 * 60 * 60
        })
      )
      const newAccess = `${header}.${payload}.refreshed`
      window.fetch = ((input: RequestInfo | URL) => {
        const url = typeof input === 'string' ? input : (input as Request).url || String(input)
        if (url.includes('/api/reels')) {
          w.__apiHits += 1
          if (w.__apiHits === 1) {
            return Promise.resolve(
              new Response(JSON.stringify({ error: 'jwt expired' }), {
                status: 401
              })
            )
          }
          return Promise.resolve(
            new Response('[]', { status: 200 })
          )
        }
        if (url.includes('/auth/v1/token')) {
          return Promise.resolve(
            new Response(
              JSON.stringify({
                access_token: newAccess,
                token_type: 'bearer',
                expires_in: 3600,
                expires_at: Math.floor(Date.now() / 1000) + 3600,
                refresh_token: 'r2',
                user: {
                  id: '00000000-0000-0000-0000-000000000001',
                  email: 'e2e@reels-bench.local'
                }
              }),
              { status: 200 }
            )
          )
        }
        return Promise.resolve(new Response('{}', { status: 200 }))
      }) as typeof fetch
    })

    await page.locator('[data-testid="open-editor-button"]').click()
    await openAiMenu(page)
    await page.locator('[data-testid="open-prefill-dialog"]').click()
    // Empty state shows once the retry succeeds with [].
    await expect(page.locator('[data-testid="prefill-empty"]')).toBeVisible({
      timeout: 8000
    })
    const hits = await page.evaluate(() => {
      const w = window as unknown as { __apiHits: number }
      return w.__apiHits
    })
    expect(hits).toBe(2)
  })
})

test.describe('@phase-3-prefill download IPC surface', () => {
  let launched: LaunchedApp | null = null

  test.beforeEach(async () => {
    launched = await launchElectron()
  })

  test.afterEach(async () => {
    if (launched) {
      try {
        await launched.app.close()
      } catch {
        /* ignore */
      }
      launched = null
    }
  })

  test('download bridge surface is exposed', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched
    await page.waitForFunction(() => !!window.electron?.download, null, {
      timeout: 5000
    })
    const keys = await page.evaluate(() => {
      const d = (window as unknown as {
        electron: { download: Record<string, unknown> }
      }).electron.download
      return Object.keys(d).sort()
    })
    expect(keys).toEqual(['downloadVideoToTemp'])
  })

  test('downloadVideoToTemp rejects non-https URLs', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched
    const r = await page.evaluate(async () => {
      return window.electron.download.downloadVideoToTemp(
        'http://example.com/x.mp4',
        'x.mp4'
      )
    })
    expect(r.ok).toBe(false)
    if (!r.ok) {
      expect(r.error).toMatch(/https/i)
    }
  })

  test('downloadVideoToTemp rejects localhost', async () => {
    if (!launched) throw new Error('launch failed')
    const { page } = launched
    const r = await page.evaluate(async () => {
      return window.electron.download.downloadVideoToTemp(
        'https://localhost/x.mp4',
        'x.mp4'
      )
    })
    expect(r.ok).toBe(false)
    if (!r.ok) {
      expect(r.error).toMatch(/localhost/i)
    }
  })
})
